Kostichev Homework 15
eugene-okulik/SergeyKostichev pull request #14
Opened 2024-10-11 08:08 UTC by kostichs

Код работает, но, наверное, лучше второй раз-то не запускать, а то дублирующие студенты, предметы, книги, уроки будут в базе. С другой стороны, айди у группы будет новая, так что ни с кем теоретически не пересечется.

2024-10-12 09:31 UTC, eugene-okulik requested changes
По заданию, сначала нужно было создать студента, потом группу, а потом определить студента в группу. Ты выполнил в другом порядке.

2024-10-12 09:45 UTC, kostichs commented
Не совсем понял, но даже у тебя по видео первый запрос на создание студента не срабатывает, ошибка в базе данных, что группы не существует. Ты пишешь второй запрос на создание группы, а потом выполняешь первый запрос по студенту. Я и подумал, что сначала нам нужна группа, а потом туда запишем студентом. 
Сейчас я могу определить студентов в неправильную группу, затем переместить их в созданную группу. Так?

2024-10-12 10:59 UTC, kostichs commented
Создаю запрос без указания группы и отправляю на выполнение, потом создаю группу, возвращаюсь к студентам и назначаю им эту группу. Done

2024-10-14 09:34 UTC, eugene-okulik commented
> Не совсем понял, но даже у тебя по видео первый запрос на создание студента не срабатывает, ошибка в базе данных, что группы не существует. Ты пишешь второй запрос на создание группы, а потом выполняешь первый запрос по студенту. Я и подумал, что сначала нам нужна группа, а потом туда запишем студентом. Сейчас я могу создать студентов в неправильную группу, затем переместить их в созданную группу. Так?

Неа, можно или создать студента с `NULL` вместо группы или поле group_id вообще не заполнять - оно автоматически заполнится правильным значением.  
Если непонятно как выполнить задание, ты спрашивай. У меня нет заданий, которые невозможно выполнить так, как они написаны.

2024-10-14 10:34 UTC, eugene-okulik requested changes

2024-10-14 10:34 UTC, eugene-okulik commented on homework/sergey_kostichev/Homework_15/py_plus_sql.py
> +                   (student_name, student[1]))
Так ты всем полным тёзкам проставишь одну и ту же группу. Нужно к данным обращаться таким образом, чтобы мы всегда были уверены в том, что мы обращаемся именно к той строке, к которой хотим. А это можно сделать только с помощью айди. Поэтому, при добавлении студентов, нужно сохранять их айди, а потом ими пользоваться.

2024-10-14 10:34 UTC, eugene-okulik commented on homework/sergey_kostichev/Homework_15/py_plus_sql.py
> +    student_ids.append(cursor.lastrowid)
А здесь ты еще раз студентов добавляешь

2024-10-14 11:59 UTC, eugene-okulik approved these changes

2024-10-14 11:59 UTC, merged