Kostichev homework 21
eugene-okulik/SergeyKostichev pull request #20
Opened 2024-10-17 09:38 UTC by kostichs

Разделить эндпоинты на классы, это просто улёт! Я слышал про page model object, но не думал, что такой же принцип можно тут применить. Это просто вау! Спасибо!
А ну и есть вопрос: дело в том, что для многих классов унаследованных от эндпоинта будут повторяться те или иные проверки. Сейчас они у меня в каждом классе прописаны, но может нужно их всех в родителя запихнуть. Для примера, у родителя можешь видеть delete метод. Но я не рискнул все яйца в одну корзину складывать.

2024-10-17 16:46 UTC, eugene-okulik commented
> Разделить эндпоинты на классы, это просто улёт! Я слышал про page model object, но не думал, что такой же принцип можно тут применить. Это просто вау! Спасибо! А ну и есть вопрос: дело в том, что для многих классов унаследованных от эндпоинта будут повторяться те или иные проверки. Сейчас они у меня в каждом классе прописаны, но может нужно их всех в родителя запихнуть. Для примера, у родителя можешь видеть delete метод. Но я не рискнул все яйца в одну корзину складывать.

Смотри, метод делит должен быть описан в классе делита. Класс делита наследуется от базового класса, для этого базовый класс импортируется в файл. Если пытаться пытаться вынести доступ к методу делит в базовый класс, то в файле базового класса придется импортнуть класс делита. А это вызывает кольцевые импорты и питон начинает ругаться сам на себя )))

2024-10-17 16:59 UTC, kostichs commented
тогда я точно, что-то не так понял :( 
сейчас у меня классы создать, изменить, удалить, получить. Но для независимых тестов, мне нужны иногда дефолтные объекты, я их создаю, а потом изменяю или удаляю. И в каждом классе у меня теперь есть свои requests.post requests.delete. Если нужно создать объект, я его создаю через объект класса создать_объект, внутри есть у его свой метод, когда нужно будет его удалить. Или когда мне нужно протестировать удаление, в классе удалить_объект, есть метод, где объект создается. У меня сейчас такая паутина получается, я хоть немного близок к решению?)))

2024-10-17 17:11 UTC, eugene-okulik requested changes

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/create_object.py
> +        self.response_json = self.response.json()
response_json не может вычитаться из респонсов со статусом не 200 и 201, да? Просто не вычитывай тогда. Помести это под try - except.

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/delete_object.py
> +        assert self.response.status_code == 200, f"Unexpected status code: {self.response.status_code}"
Ну, я уже писал, что это должно быть в базовом классе, как я показывал в видео и не нужно будет в каждый класс это вставлять.

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/delete_object.py
> +            f"Object with ID {test_object_id} was not deleted"
Этот метод должен называться check_response_404 и находиться в базовом классе. А сам get запрос уже находится в классе GetObject

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/delete_object.py
> +        assert self.response.status_code == 404, f"Unexpected status code: {self.response.status_code}"
Этот метод должен быть двумя. Точнее первый - удаление по id у тебя уже есть. А второй - check_response_404, который ты добавишь в базовый класс.

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/get_object.py
> +        assert self.response.status_code == 200, f"Unexpected status code: {self.response.status_code}"
Это уже в базовом классе, да?

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/endpoints/get_object.py
> +        requests.delete(f"{self.url}/object/{object_id}")
И здесь этому не место.

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_post_endpoint.delete_object(create_post_endpoint.response)
А зачем его удалять - он же не создастся. Да и в create_post_endpoint.response хранится что-то типа response<400> - не очень похоже на id )))

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    update_object_endpoint.check_negative_data(data=data, method='PUT')
Здесь должно быть несколько шагов: первый - отправка запроса с негоативными данными, второй - проверка, что ответ соответствует ожидаемому.

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_delete_endpoint.check_delete_non_existent_object(fake_id)
А здесь первый шаг
```python
create_delete_endpoint.delete_object(fake_id)
```
и второй шаг
```python
create_delete_endpoint.check_response_404()
```

2024-10-17 17:11 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +        create_get_endpoint.check_not_found(none_id)
Параметризованный тест это тест, который выполняет одинаковые действия, но с разными тестовыми данными. Здесь ты просто в один тест поместил два. Первый перед else, второй после

2024-10-18 04:25 UTC, kostichs commented on test_api_skostichev/conftest.py
> +def create_delete_endpoint():
да, я неправильно понял значение ендпоинта, думал, что так ты называешь хттп методы, поэтому это было вроде создать_делете_метод. Переделал просто в делете_эндпоинт

2024-10-18 04:27 UTC, kostichs commented on test_api_skostichev/conftest.py
> +    test_object.delete_object(test_response.json()["id"])
а я подумал, что это ресурсоемко, создавать каждый раз объект, чтобы использовать для удаления чего-то. Хотя я могу указать scope=session, чтобы их на каждый тест не создавать

2024-10-18 04:39 UTC, kostichs commented on test_api_skostichev/tests/test_api.py
> +    create_post_endpoint.delete_object(create_post_endpoint.response)
когда по первым комментариям начал исправление, тоже обратил внимание на это. Но очень удивился, что код на это не ругался и тесты были зелеными. Убрал

2024-10-18 05:40 UTC, kostichs commented
![image](https://github.com/user-attachments/assets/c3d69ab5-98cf-44e7-9550-cc0384bae619)
Странное поведение у пайчарма с зависимостями, эта функция точно используется, как и другие, но зависимости не отображаются.

2024-10-18 05:43 UTC, kostichs commented on test_api_skostichev/endpoints/update_object.py
> +class UpdateObject(Endpoint):
подумал, что раз у них одинаковые методы, то объединить их в один. Может стоит создать базовый класс для этих двух? Ендпоинт родитель для Update который родитель для FullUpdate и PartUpdate?

2024-10-18 09:10 UTC, eugene-okulik requested changes

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/endpoints/endpoint.py
> +        assert self.response.status_code in [400, 404, 405], f"Unexpected status code: {self.response.status_code}"
Такая универсальность до добра не доведет. Иногда важно проверить, что пришла именно ошибка 400, а 404 при этом будет считаться багом.

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/endpoints/get_object.py
> +        assert self.response.status_code == 404, f"Expected 404 but got {self.response.status_code}"
Этого метода не должно быть. Первая его часть уже реализована в методе get_object, вторая его часть реализовата в базовом классе.

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/endpoints/update_object.py
> +class PartUpdateObject(Endpoint):
Счиатется хорошим тоном для каждого класса создавать отдельный файл.

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_post_endpoint.check_status_request_400(data=data)
В этом тесте должно быть два шага: первый делает запрос с негативными данными, второй проверяет что статус код = 400

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    delete_endpoint.verify_object_deleted(create_test_response)
Вместо этой строки должно быть две других: первая - получение объекта по айди с помощью метода get_object в классе GetObject; вторая - проверка, что статус код ответа = 404

2024-10-18 09:10 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_get_endpoint.check_not_found(none_id)
Для этого теста не нужна отдельная функция, нужно пользоваться существующими: 1 - получение объекта, 2 - проверка, что статус код ответа = 404

2024-10-18 09:19 UTC, kostichs commented on test_api_skostichev/endpoints/endpoint.py
> +        assert self.response.status_code in [400, 404, 405], f"Unexpected status code: {self.response.status_code}"
дело в том, что у меня действительно падает все с 400, и один какой-то параметр дает 404, я на него не проверяю, но могу добавить такой кейс с методом, где будет проверяться 404

2024-10-18 10:28 UTC, kostichs commented on test_api_skostichev/tests/test_api.py
> +    delete_endpoint.verify_object_deleted(create_test_response)
просто уточнить, у тебя же опечатка здесь, ты хотел написать код 200?

2024-10-19 08:25 UTC, eugene-okulik commented on test_api_skostichev/endpoints/update_object.py
> +class UpdateObject(Endpoint):
Можно сделать для них базовый, да, если видишь, что какие-то из методов для них могут быть общими.

2024-10-19 08:27 UTC, eugene-okulik commented on test_api_skostichev/conftest.py
> +    test_object.delete_object(test_response.json()["id"])
это вообще никак не затрачивает ресурсы. А scope=session будет за всё время тестовой сессии накабливать в себе кучу ненужного и в какой-то момент будешь не понимать откуда растут ноги у какой-то проблемы.

2024-10-19 08:28 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_post_endpoint.delete_object(create_post_endpoint.response)
ну у тебя нет проверки статуса - вот ничего и не ругалось. А там приходила 404, так как объекта с айди response<400> нет.

2024-10-19 08:38 UTC, eugene-okulik approved these changes
ВОот теперь хорошо. Есть мелкие нюансы, но это уже ерунда.

2024-10-19 08:38 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    delete_endpoint.delete_object(create_post_endpoint.response)
И здесь ты удаляешь 
```python
delete_endpoint.delete_object(Response<200>)
```

2024-10-19 08:38 UTC, eugene-okulik commented on test_api_skostichev/tests/test_api.py
> +    create_get_endpoint.get_object(create_test_response)
А для чего шаг create_get_endpoint.get_object(create_test_response), если его результат никак не проверяется?

2024-10-19 08:38 UTC, eugene-okulik commented on test_api_skostichev/endpoints/delete_object.py
> +        assert response.status_code == 404, f"Unexpected status code: {response.status_code}"
Если не ошибаюсь, этот метод уже нигде не используется и не нужен. А если используется, то нужно перестать его использовать )))

2024-10-19 08:38 UTC, eugene-okulik commented on test_api_skostichev/endpoints/delete_object.py
> +            test_object_id = test_object["id"]
А, вот ты как замутил, ну, тогда response<200> нормально прокатит )))

2024-10-19 08:38 UTC, eugene-okulik commented on test_api_skostichev/endpoints/get_object.py
> +        assert self.response.status_code == 404, f"Expected 404 but got {self.response.status_code}"
И этот метод вроде бы уже не используется, ну, по крайней мере, не должен.

2024-10-19 08:38 UTC, merged

2024-10-19 08:48 UTC, kostichs commented on test_api_skostichev/endpoints/delete_object.py
> +        assert response.status_code == 404, f"Unexpected status code: {response.status_code}"
да, точно, забыл удалить, после того, как все проверки перевел на check_400 check_404 методы. Спасибо)