Added homework
eugene-okulik/SergeyKostichev pull request #24
Opened 2024-11-14 20:02 UTC by kostichs

Playwright не работает для радиокнопок и чекбоксов (что удивительно, для одних элементов он находит по айди, а для других начинает прыгать страница и ничего не находит).  к сожалению, очень много времени с этим базовым заданием потерял.

2024-11-15 07:00 UTC, eugene-okulik commented
> Playwright не работает для радиокнопок и чекбоксов (что удивительно, для одних элементов он находит по айди, а для других начинает прыгать страница и ничего не находит). к сожалению, очень много времени с этим базовым заданием потерял.

В этом и есть вся заморочка автоматизации. Если бы всё делалоь напрямую, так, как с первого взгляда кажется должно работать, то автоматизаторы за один день бы всё автоматизаировали и сидели смотрели кк их тесты сами работают. Большая часть работы автоматизатора заключается в том, чтобы найти стабильный способ выполнения необходимых действий.

2024-11-15 07:02 UTC, eugene-okulik requested changes
Нужно убрать весь закоментированный код и оставить только тот код, который относится к выполнению задания

2024-11-16 06:56 UTC, eugene-okulik requested changes

2024-11-16 06:56 UTC, eugene-okulik commented on homework/sergey_kostichev/Homework_25/test_demoqa.py
Не выбран пол, не выбраны хобби. Подумай как ты как пользователь взаимодействуешь с такими элементами. Всегда ли ты кликаешь прямо по кружочку радиобаттона? Или кликаешь по лейблу этого радиобаттона?  
Как автоматизатор, ты должен всегда найти способ сделать то, что нужно сделать. Эту форму, такую кривую, я даю специально, чтобы потренироваться в поиске нестандартных решений.

2024-11-16 06:56 UTC, eugene-okulik commented on homework/sergey_kostichev/Homework_25/test_role.py
> +    time.sleep(2)
Слипов в тесте не должно быть. А, тем более, это Playwright. В нем все ожидания происходят автоматически.

2024-11-16 09:18 UTC, kostichs commented
@eugene-okulik если убрать time sleep, то код выполняет все одновременно, в том числе нажатие кнопки, когда форма еще не заполнена..

2024-11-17 08:03 UTC, eugene-okulik commented
> @eugene-okulik если убрать time sleep, то код выполняет все одновременно, в том числе нажатие кнопки, когда форма еще не заполнена..

Не вижу такого эффекта, но если бы он был, то решать это нужно не слипами, а ожиданиями. Использование слипа настолько плохо, что нужно считать, что такой функциональности ввобще нет в питоне. Слипы могут спровоцировать бесконтрольные падения работы программы и слипы затягивают выполнение тестов независимо от того нужны они или нет.

2024-11-17 08:03 UTC, eugene-okulik approved these changes

2024-11-17 08:03 UTC, merged