Implemented testing magento pages on playwright
eugene-okulik/SergeyKostichev pull request #27
Opened 2024-12-08 13:14 UTC by kostichs

Не понравился мне ваш playwright, таких истерик у меня давно не было))

2024-12-09 07:50 UTC, eugene-okulik requested changes

2024-12-09 07:50 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/account_creation_page.py
> +                "Invalid answer when all fields are True"
Ожидаемый текст является тестовыми данными. Тестовые данные должны даваться этому методу из теста. Кроме того, этот метод не только что-то делает, но и проверяет. Поэтому, название этого метода должно отражать это. Пока что кажется, что в методе нет проверок.

2024-12-09 07:50 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/account_creation_page.py
> +            'Please enter the same value again.')
Здесь тоже текст - это тестовые данные и название метода не говорит о том, что в методе есть не только действие, но и проверка.

2024-12-09 07:50 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/collections_page.py
> +    def add_to_cart(self, size_and_colors=True):
Этот метод или должен ждать, что есму укажут какой товар добавить в корзину, или, если он добавляет рандомный товар, нужно, чтобы название об этом говорило.

2024-12-09 07:50 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/collections_page.py
> +        except Exception:
Такие эксепшены - слишком широкие. При пропадании интернета или падении сайта метод тоже перейдет в этот Except. Нужно обрабатывать только те ексепшены, при которых есть смысл выполнять следующую строку.

2024-12-09 07:50 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/collections_page.py
> +        }
В целом, этот метод слишком громоздкий и покрывает несколько степов и проверяет несколько разных ошибок. Нужно или всё это написать в названии или сделать несколько методов.

2024-12-09 07:51 UTC, eugene-okulik commented
> Не понравился мне ваш playwright, таких истерик у меня давно не было))

о, прикольно. Я не один не в восторге от плейрайта. Обычно наоборот. Все влюбляются в плейрайт. А тебе он чем не зашел?

2024-12-09 09:07 UTC, kostichs commented on test_ui_kostichev_pw/pages/account_creation_page.py
> +            'Please enter the same value again.')
вот здесь я не понял, разве текст лейблов, сообщающих об ошибках или успешном создании аккаунта, это не часть пейджа, разве это тестовые данные? Мой тест на то, что эта часть пейджа отрабатывает верно

2024-12-10 06:47 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/account_creation_page.py
> +            'Please enter the same value again.')
"Please enter the same value again." - вот это тестовые данные

2024-12-10 06:54 UTC, eugene-okulik approved these changes

2024-12-10 06:54 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/account_creation_page.py
> +                expect(self.page.locator(error_element_id)).to_have_text('This is a required field.')
Здесь тестовые данные из метода не убрал

2024-12-10 06:54 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/collections_page.py
> +    def sort_by_price(self):
Этот метод не только сортирует, но и проверяет что-то, нужно, чтобы из названия это было понятно.

2024-12-10 06:54 UTC, eugene-okulik commented on test_ui_kostichev_pw/pages/sale_page.py
> +    def open_all_sale_offers(self):
И этот не только открывает, но и проверяет, а в названии об этом не сказано

2024-12-10 06:55 UTC, merged